-- Creates user_profile table

CREATE TABLE user_profile (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY         PRIMARY KEY,
  username      VARCHAR(100)                                    NOT NULL UNIQUE
);
